services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: cadma
      POSTGRES_USER: cadma
      POSTGRES_PASSWORD: cadma
    ports:
      - "55432:5432"  # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
