services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: cadma
      POSTGRES_USER: cadma
      POSTGRES_PASSWORD: cadma
    ports:
      - "55432:5432"  # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_ENV: local
      DJANGO_DEBUG: '1'
      DJANGO_SECRET_KEY: dev-key
      POSTGRES_DB: cadma
      POSTGRES_USER: cadma
      POSTGRES_PASSWORD: cadma
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
