# Generated by Django 5.2.5 on 2025-08-31 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmaflow_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se congeló la definición (inmutable)', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='frozen_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que congeló la definición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('DATA_FROZEN', 'Datos Congelados')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='branch_label',
            field=models.CharField(blank=True, help_text='Etiqueta descriptiva de la rama para UI', max_length=100),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='current_step_index',
            field=models.IntegerField(default=0, help_text='Índice (orden) del próximo step a ejecutar'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='parent_execution',
            field=models.ForeignKey(blank=True, help_text='Ejecución padre si esta es una rama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='cadmaflow_models.workflowexecution'),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='input_data_snapshot',
            field=models.JSONField(default=dict, help_text='Snapshot de los datos de entrada congelados (moléculas + propiedades usadas)'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='branch_label',
            field=models.CharField(blank=True, help_text="Etiqueta legible de la rama (ej: 'v2-high-temp')", max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='branch_of',
            field=models.ForeignKey(blank=True, help_text='Workflow padre del que se bifurca esta definición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_branches', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción funcional / propósito'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='key',
            field=models.CharField(help_text='Identificador estable para referenciar el workflow', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(help_text='Nombre legible del workflow', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='root_branch',
            field=models.ForeignKey(blank=True, help_text='Workflow raíz del árbol al que pertenece esta rama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowbranch',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow blueprint al que pertenece la rama', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='current_step',
            field=models.CharField(blank=True, help_text='ID lógico del último step completado', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('DATA_FROZEN', 'Datos Congelados')], default='PENDING', help_text='Estado global de la ejecución', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow blueprint de esta ejecución', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cadmaflow_models.workflow'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['status'], name='cadmaflow_m_status_8f944d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['branch_of'], name='cadmaflow_m_branch__88a5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['root_branch'], name='cadmaflow_m_root_br_ebfc30_idx'),
        ),
    ]
