# Generated by Django 5.2.5 on 2025-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmaflow_models', '0003_absorptiondata_logpdata_mutagenicitydata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowbranch',
            name='branch_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
