# Generated by Django 5.2.5 on 2025-08-31 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmaflow_models', '0005_alter_workflowbranch_branch_reason_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflow',
            name='cadmaflow_m_status_8f944d_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='cadmaflow_m_branch__88a5ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='cadmaflow_m_root_br_ebfc30_idx',
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='data_retrieval_methods',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='input_data_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='input_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='branch_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='branch_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_branches', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='key',
            field=models.CharField(help_text='Identificador estable', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='root_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowbranch',
            name='data_selection_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workflowbranch',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='cadmaflow_models.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='branch_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='current_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='current_step_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='family_data_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='parent_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='cadmaflow_models.workflowexecution'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('DATA_FROZEN', 'Datos Congelados')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cadmaflow_models.workflow'),
        ),
    ]
