name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ci
      DJANGO_SECRET_KEY: ci-secret
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: ci_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U ci_user" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests & coverage
        run: |
          pytest --cov=cadmaflow --cov-report=xml --cov-report=term-missing
      - name: Reportar covertura y mandar error si no pasa la covertura mayor al 85
        run: |
          if [[ $(pytest --cov=cadmaflow --cov-report=xml --cov-report=term-missing | tail -n 1) < "85.00%" ]]; then
            echo "La cobertura de pruebas es menor al 85%"
            exit 1
          fi